import type { Metadata } from "next";
import { cookies, headers } from "next/headers";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import UserProvider, { UserContext } from "@/lib/user-provider";
import client from "@/api/client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const res = await client.GET("/api/auth/me", {
		headers: headers(),
	});

	return (
		<html lang="en">
			<UserProvider user={res.data?.user ?? null}>
				<body className={inter.className}>
					<main className="w-full h-full">{children}</main>
					<Toaster />
				</body>
			</UserProvider>
		</html>
	);
}
